#!/usr/bin/env python3
"""Give every APPLICABLE registry ID a truthful, per-ID accounted result.

WHY THIS EXISTS. The applicability matrix declared 49 of the 484 registry IDs
APPLICABLE and, for most of them, named an executable harness entry point that
exists in this repository. Forty-one of those IDs nevertheless carried the same
blanket accounting reason: "no candidate-specific case material executed for this
ID ... Real dependency/harness provisioning is required before a truthful PASS or
N/A decision can be recorded."

That string is FALSE for the majority of them -- the harness exists, is an enforced
lane, and passes -- and where it is true it names no material at all. A blanket
excuse covering 41 different capabilities is the same defect class as the 423 IDs
decided by one string and the DOD-041 probe decided by a bare token, both already
corrected in this run.

WHAT THIS SCRIPT DOES
  --write   runs the citations in CASES, which are re-read from real sources:
            * git-tracked gate logs captured by `.agent/state/applicable-case-runs.py`
            * `.agent/evidence/applicable-cases/logs/probes.log` (architecture probes)
            * evidence artifacts regenerated by the verification pipeline
            * first-party source symbols
            A citation that cannot be verified ABORTS the run: a document may not
            cite a line, a symbol, or an artifact that is not there.
            It then writes one evidence document per ID and upserts the ID's row in
            CASE_RESULTS.json (status, evidence_path, reason).
  --check   re-verifies every citation and every generated document against the
            current tree, so a regenerated artifact cannot silently invalidate a
            quoted line. Wired into scripts/verify.sh as a currency lane.

Statuses are decided per ID from what the citations actually show: PASS, PARTIAL
(part of the capability is exercised and the missing part is named), or
NOT_RUN_BLOCKED_MATERIAL with the specific material NAMED (the four IDs whose
subject does not exist in this architecture).
"""
from __future__ import annotations

import csv
import hashlib
import json
import pathlib
import sys

ROOT = pathlib.Path(".").resolve()
MATRIX = ROOT / ".agent/verification/APPLICABILITY_MATRIX.csv"
REGISTRY = ROOT / ".agent/verification/MASTER_TEST_REGISTRY.csv"
CASE_RESULTS = ROOT / ".agent/verification/state/CASE_RESULTS.json"
RUNS = ROOT / ".agent/evidence/applicable-cases/RUNS.json"
EPOCH = ROOT / ".agent/verification/state/EPOCH.json"
PROBES = ROOT / ".agent/evidence/applicable-cases/logs/probes.log"
LOGS = ROOT / ".agent/evidence/applicable-cases/logs"
OUT = ROOT / ".agent/evidence/applicable-cases"

# citation kinds:
#   ("run", key, [required substrings of that log])
#   ("probe", "<exact probe log line>")
#   ("artifact", path, [required substrings])
#   ("source", path, [required substrings])
CASES: dict[str, dict] = {
    "GEN-001": {
        "status": "PASS",
        "cites": [
            ("run", "lint", ["lint: Done", "Finished `dev` profile"]),
            ("run", "fmt", []),
            ("run", "anti-gaming", []),
            ("run", "security-check", ["security-check: ok"]),
        ],
        "finding": "The static-analysis lane runs clippy over the whole workspace with all targets and warnings denied, ESLint over all three JS packages, and a rustfmt check; every lane exited 0 on this candidate. The security gate additionally runs a lexical anti-gaming scan for fabricated behaviour and requires each match to be classified.",
        "not_proven": "No dedicated multi-rule SAST engine or dataflow/taint analysis is installed; the depth here is compiler lints, lint rules and a lexical scan.",
    },
    "GEN-002": {
        "status": "PASS",
        "cites": [
            ("run", "deny-advisories", ["advisories ok"]),
            ("run", "deny-bans", []),
            ("run", "deny-sources", ["sources ok"]),
            ("run", "pnpm-audit", ["Severity: 2 moderate"]),
        ],
        "finding": "Composition analysis executed against the locked graphs of both ecosystems: cargo-deny advisories/bans/sources and `pnpm audit --audit-level high`, all exit 0.",
        "not_proven": "The npm audit reports 2 moderate advisories; they are below the enforced high threshold and are dev-only, which is a disclosed accepted risk rather than a clean bill.",
    },
    "GEN-003": {
        "status": "PASS",
        "cites": [
            ("run", "deny-advisories", ["advisories ok"]),
            ("run", "pnpm-audit", []),
            ("artifact", ".agent/evidence/sbom/linchpin.cdx.json", ['"bomFormat"', '"CycloneDX"']),
        ],
        "finding": "Dependency scanning executed for both ecosystems against committed locks, and the resulting component inventory is materialised as a CycloneDX SBOM with 720 components.",
        "not_proven": "Scanning is per-candidate, not continuous: no scheduled re-scan runs between candidates, so an advisory published later is only seen on the next run.",
    },
    "GEN-004": {
        "status": "PASS",
        "cites": [
            ("run", "deny-licenses", ["licenses ok"]),
            ("run", "security-check", ["security-check: ok"]),
            ("artifact", ".agent/evidence/sbom/linchpin.cdx.json", ['"licenses"']),
            ("source", "deny.toml", ["MPL-2.0"]),
        ],
        "finding": "Licence compliance executed: `cargo deny check licenses` exits 0 against an explicit allowlist (MPL-2.0 permitted under ACCEPTED ADR-002), and the SBOM generator enforces the same allowlist so the scanner and the inventory cannot disagree.",
        "not_proven": "Four allowlist entries were never encountered in the graph (Apache-2.0 WITH LLVM-exception, BSD-2-Clause, ISC, Unicode-DFS-2016), so the policy is broader than the measured graph requires; licence classification comes from crate metadata, not from a legal review of texts.",
    },
    "GEN-005": {
        "status": "PASS",
        "cites": [
            ("run", "secret-scan", ["secret-scan check: ok (9 rules, no findings)"]),
            ("run", "security-check", ["security-check: ok"]),
        ],
        "finding": "Secret scanning executed as an enforced lane with 9 rules over the git-tracked tree, reporting no findings on this candidate.",
        "not_proven": "The scan is pattern-based over tracked text: it does not scan git history, ignored or untracked files, or binaries, and it cannot detect a credential shape no rule describes.",
    },
    "GEN-006": {
        "status": "PASS",
        "cites": [
            ("run", "secret-scan", ["secret-scan check: ok (9 rules, no findings)"]),
            ("source", "crates/crash_reporter/src/lib.rs", ["redact_key_values"]),
            ("probe", "concern[redaction]_tests: 21"),
            ("artifact", ".agent/evidence/fuzz/STATUS.md", ["panic"]),
            ("artifact", ".agent/evidence/mutation-proof/REPORT.json", ["MUT-OPS-037"]),
        ],
        "finding": "Credential scanning executed at two layers: the repository-wide scan, and the product's own redaction policy (21 redaction/secret/credential tests), whose discrimination is proven by mutation MUT-OPS-037 -- removing the key-value redaction pass makes the guarding test fail.",
        "not_proven": "Runtime redaction only removes values it can attribute to a key name or a known token shape; unlabelled credential material pasted as free text is not detectable by either layer.",
    },
    "GEN-007": {
        "status": "PASS",
        "cites": [
            ("run", "secret-scan", ["secret-scan check: ok (9 rules, no findings)"]),
            ("source", "crates/crash_reporter/src/lib.rs", ["redact_key_values", "looks_like_secret"]),
            ("probe", "concern[redaction]_tests: 21"),
        ],
        "finding": "Hardcoded-credential detection executed: the tracked tree is scanned, and the shipping redactor detects credential shapes at runtime (`looks_like_secret`, `redact_key_values`) with the defect history recorded rather than tidied -- an earlier version both leaked short credentials and panicked on case-folding characters, and both were fixed with regression tests.",
        "not_proven": "Pattern rules cover known provider shapes; a fabricated or unusual credential format in source would not be flagged by either layer.",
    },
    "GEN-024": {
        "status": "PASS",
        "cites": [
            ("artifact", ".agent/evidence/fuzz/STATUS.md", ["fuzz_campaign.rs", "4 634 inputs per target"]),
            ("source", "apps/desktop/src-tauri/tests/fuzz_campaign.rs", ["deterministic"]),
            ("artifact", ".agent/evidence/mutation-proof/REPORT.json", ["MUT-FUZZ-001"]),
        ],
        "finding": "Mutation-based fuzzing executed: a seeded, deterministic campaign over ten IPC-reachable parsers (4 634 adversarial inputs per target plus 20 000 random mutations) with reproducible shrinking. It found a real panic in the credential redactor, and the campaign is itself mutation-proven by MUT-FUZZ-001.",
        "not_proven": "No coverage-guided engine and no nightly sanitizers; the campaign is labelled ABBREVIATED because no fuzzing scale is specified for this registry ID.",
    },
    "GEN-035": {
        "status": "PASS",
        "cites": [
            ("artifact", ".agent/evidence/artifact-e2e/STATUS.md", ["linchpin-desktop-e2e.exe", "DevTools endpoint", "tauri.localhost"]),
            ("source", "scripts/artifact-e2e.sh", ["does NOT open a debug port"]),
            ("source", "apps/desktop/src-tauri/src/commands.rs", ["test_export_firewall_blocks_restricted_content"]),
        ],
        "finding": "Desktop application security testing executed against the packaged executable: the loaded origin is the embedded frontend rather than a dev server, the production artifact is asserted to open no debug port, and the confidentiality boundary (disclosure firewall, export blocking) is exercised.",
        "not_proven": "There is no third-party penetration test and no fuzzing of the WebView2 attack surface; the debug-port assertion is a liveness-checked probe of the exact artifact, not a full network attack simulation.",
    },
    "GEN-042": {
        "status": "PASS",
        "cites": [
            ("run", "deny-advisories", ["advisories ok"]),
            ("run", "pnpm-audit", ["2 vulnerabilities found"]),
            ("run", "security-check", ["security-check: ok"]),
        ],
        "finding": "Vulnerability scanning executed for both ecosystems against the RustSec and npm advisory databases, with the enforced threshold stated and the two moderate dev-only npm advisories disclosed rather than suppressed.",
        "not_proven": "No container or image scanning applies (there is no container), and no host-level vulnerability scan of the operator machine is performed.",
    },
    "GEN-044": {
        "status": "PARTIAL",
        "cites": [
            ("artifact", ".agent/evidence/ANTI_GAMING_FINDINGS.md", ["AG-001", "AG-014"]),
            ("probe", "concern[redaction]_tests: 21"),
        ],
        "finding": "Fourteen fabricated-behaviour findings (AG-001..AG-014) and the fuzz-found panic are recorded with root cause, and the weakness families they represent are identifiable (CWE-703 for the panic, CWE-20 for traversal/validation gaps, CWE-798 for the planted-credential proof).",
        "not_proven": "NOT PASS: the CWE mapping is prose in the findings file, not a machine-readable weakness column per finding, and no dedicated weakness-enumeration scanner runs.",
    },
    "GEN-045": {
        "status": "PASS",
        "cites": [
            ("source", "crates/evidence/src/lib.rs", ["sanitize_path", "test_archive_entry_rejects_zip_slip"]),
            ("probe", "concern[traversal]_tests: 3"),
            ("source", "crates/provider_transport/src/lib.rs", ["test_local_adapter_rejects_non_loopback_endpoint"]),
            ("artifact", ".agent/evidence/fuzz/STATUS.md", ["fuzz_campaign.rs"]),
        ],
        "finding": "Injection testing executed at the boundaries this product has: path/zip-slip hardening with a generated-corpus property test, fuzzed text parsers, punctuation-quoted credential forms in the redactor, and the local provider refusing a non-loopback endpoint.",
        "not_proven": "There is no SQL-injection or HTML-injection scan by a dedicated tool; the datastore is accessed through parameterised statements and the UI through React, both covered by tests rather than by an injection scanner.",
    },
    "GEN-049": {
        "status": "PASS",
        "cites": [
            ("probe", "concern[validation]_tests: 23"),
            ("source", "crates/commercialization/src/asset_readiness.rs", ["test_invalid_records_are_refused"]),
            ("source", "crates/evidence/src/lib.rs", ["sanitize_path"]),
        ],
        "finding": "Input validation executed: 23 boundary/invalid-input tests across the domain, commercialization, evidence and IPC layers, covering empty values, unknown identities, blank references, malformed dates, invalid record kinds and hardened paths.",
        "not_proven": "Validation depth is per-command and typed (SPEC-006 classes) rather than driven by a schema-fuzzing harness; there is no property-based generator over the full command surface.",
    },
    "GEN-051": {
        "status": "NOT_RUN_BLOCKED_MATERIAL",
        "cites": [
            ("probe", "auth_surface_hits: 0"),
            ("probe", "mcp_capability_grant_hits: 11"),
            ("probe", "disclosure_firewall_hits: 42"),
        ],
        "material": "an authorization decision to test. A measured scan of all first-party source finds ZERO login/logout/authenticate/session-token/is-admin/role-based-access constructs: this is a local-first single-user desktop application with no caller identity, no session, no roles and no remote API, so there is no subject/object/permission triple for an authorization test to exercise. The nearest real control is the MCP capability grant (11 sites) and the disclosure firewall (42 sites), which are recorded under GEN-052. The registry pack declares this ID applicable to applications in general; the material an authorization test requires is absent from this architecture rather than missing from the harness.",
        "finding": "Measured absence of the subject of the test, with both nearest real controls measured present.",
        "not_proven": "No authorization test was executed, because executing one would require inventing an identity model the product does not have.",
    },
    "GEN-027": {
        "status": "PASS",
        "cites": [
            ("artifact", ".agent/evidence/fuzz/STATUS.md", ["fuzz_campaign.rs", "4 634 inputs per target"]),
            ("source", "apps/desktop/src-tauri/tests/fuzz_campaign.rs", ["Mutation-based fuzz campaign", "fn mutate("]),
            ("artifact", ".agent/evidence/mutation-proof/REPORT.json", ["MUT-FUZZ-001"]),
            ("source", "scripts/mutation-proof.py", ["SURVIVED", "anchor matched"]),
        ],
        "finding": "Mutation-based testing is executed at two levels, and this row used to deny both. (1) FUZZING: the campaign in apps/desktop/src-tauri/tests/fuzz_campaign.rs mutates inputs with a seeded xorshift64* generator (byte flips, insertions, deletions, splices) after its deterministic adversarial phase, and it FOUND a real panic in the credential redactor; the campaign is itself mutation-proven by MUT-FUZZ-001, which reintroduces that defect and requires the campaign to fail. (2) CONTROLLED DEFECTS: scripts/mutation-proof.py applies 13 declared mutations to production code, requires the mutant to compile, requires the named guarding test to FAIL, restores the bytes and reruns green -- it fails on SURVIVED and BUILD_ERROR, and it refuses an anchor that does not match exactly once.",
        "not_proven": "Neither mechanism is a general-purpose mutation-testing platform: coverage is the 13 declared mutations and ten fuzz targets, not the whole codebase, and no mutation-score threshold is enforced. Two earlier mutations that SURVIVED were withdrawn rather than claimed as caught.",
    },
    "GEN-057": {
        "status": "PASS",
        "cites": [
            ("source", "crates/storage/src/vault.rs", ["test_sha256_known_vector"]),
            ("source", "crates/storage/src/lib.rs", ["test_encrypted_vault"]),
            ("source", "crates/evidence/src/lib.rs", ["test_update_signature_verification"]),
            ("probe", "concern[redaction]_tests: 21"),
        ],
        "finding": "Cryptographic implementation IS tested, which this row denied. Executed: a SHA-256 known-vector test (so the hash is checked against a published value rather than against itself), an encrypted-blob container round trip, update-signature verification, content-addressed blob storage whose address is the digest of the content, and the threat-control tests that assert the secret allowlist holds no cryptographic material of its own.",
        "not_proven": "There is no cryptographic review by a specialist and no FIPS/algorithm-agility requirement to test against; the primitives are those of the pinned dependencies (SHA-256, the encrypted container's cipher), so the tests prove the product uses them correctly at the boundaries it exposes, not that the primitives themselves are sound.",
    },
    "GEN-065": {
        "status": "PASS",
        "cites": [
            ("source", "crates/platform_windows/src/lib.rs", ["test_unknown_keys_warn_in_development_and_fail_in_release"]),
            ("source", "crates/platform_windows/src/lib.rs", ["test_missing_required_value_is_an_error_not_a_fallback"]),
            ("source", "crates/platform_windows/src/lib.rs", ["test_release_runtime_is_parsed"]),
            ("artifact", ".agent/evidence/clean-build/ENVIRONMENT.json", ["toolchain"]),
        ],
        "finding": "Configuration hardening IS asserted, which this row denied: the configuration surface parses its environment ONCE into typed values, unknown keys are a warning in development and a HARD FAILURE in release, and a missing required value is an error rather than a fallback -- the fail-closed direction the hardening clause asks for. The build environment itself is pinned and recorded (toolchain, lockfile digests) by the clean-build gate.",
        "not_proven": "There is no CIS/STIG-style baseline and no scanner that compares the installed configuration against a policy; the hardening claim is bounded to the product's own configuration surface and to the release-mode behaviour its tests assert.",
    },
    "GEN-115": {
        "status": "PASS",
        "cites": [
            ("source", "apps/desktop/src-tauri/tests/recovery_drill.rs", ["faults are injected at the filesystem", "in-place corruption"]),
            ("artifact", ".agent/evidence/recovery-drill/report.json", ["fault_classes", "total_loss", "rto_ms_threshold"]),
            ("source", "apps/desktop/src-tauri/tests/stress_concurrency.rs", ["no backup completed during the trial"]),
            ("source", "scripts/fault-injection-lane.sh", ["recovery_drill"]),
        ],
        "finding": "Fault injection IS executed, which this row denied. The drill injects two fault classes repeatedly against a live vault -- TOTAL LOSS (the vault file and its WAL siblings deleted) and CORRUPTION (the live vault overwritten in place) -- then recovers through the PRODUCTION restore command and reconciles the recovered state by content digest through an independent connection, with RPO/RTO measured against an enforced threshold. The exact-artifact lane adds a hard process kill with the ledger read back in a new process, and the stress trial injects backup destruction under concurrent load.",
        "not_proven": "The faults are filesystem-level on one host: no disk-error injection, no power-loss or kernel-level fault, and no network partition (the product serves no network). The drill covers the vault, not the whole machine.",
    },
    "GEN-052": {
        "status": "PASS",
        "cites": [
            ("probe", "mcp_capability_grant_hits: 11"),
            ("probe", "disclosure_firewall_hits: 42"),
            ("source", "apps/desktop/src-tauri/src/commands.rs", ["test_mcp_capability_grant_is_explicit", "test_export_firewall_blocks_restricted_content"]),
            ("source", "crates/storage/src/vault.rs", ["test_events_are_workspace_scoped", "test_unknown_workspace_is_refused"]),
            ("source", "crates/mcp_hub/src/lib.rs", ["test_mcp_grants_and_boundaries"]),
        ],
        "finding": "Broken-access-control testing executed for the access controls this product actually has: MCP capability grants are explicit per server/client/workspace/capability and deny by default (an unknown capability and an empty grant list are both refused), the disclosure firewall blocks export of restricted content, and workspace-scoped reads do not expose another workspace's events.",
        "not_proven": "There is no multi-user or remote access-control model to break, so this ID is satisfied by the grants and the firewall rather than by role enforcement.",
    },
    "GEN-063": {
        "status": "PASS",
        "cites": [
            ("artifact", ".agent/evidence/DOD-037-operator-diagnostics.md", ["alert", "correlation", "DEGRADED"]),
            ("source", "apps/desktop/src-tauri/src/commands.rs", ["diagnostics_redactor", "record_diagnostic_outcome"]),
            ("probe", "concern[diagnostics]_tests: 16"),
        ],
        "finding": "Logging and monitoring verification executed against induced failures: the diagnostics surface reports readiness measured by probing storage, records every command outcome with measured duration and a correlation id, derives alerts from those measurements, and redaction is asserted on the same path with 16 diagnostics/health tests.",
        "not_proven": "Telemetry is device-local with no exporter, so there is no central monitoring stack to verify; alert routing beyond the in-app surface is not implemented.",
    },
    "GEN-071": {
        "status": "NOT_RUN_BLOCKED_MATERIAL",
        "cites": [
            ("probe", "sandbox_primitive_hits: 8"),
            ("probe", "sandbox_artifact[Dockerfile]: False"),
            ("probe", "sandbox_artifact[.devcontainer]: False"),
            ("probe", "sandbox_artifact[k8s]: False"),
        ],
        "material": "an isolation boundary to test. The product ships as a per-user Windows application with no container, job object, AppContainer, seccomp profile or VM boundary: no Dockerfile, devcontainer, kubernetes manifest or container runtime exists in the repository, and the only `sandbox` symbol in first-party source is a test double for git integration (`GitIntegrationSandbox`), which isolates nothing. The isolation controls that DO exist are recorded under their own IDs (loopback-only provider transport, device-local storage, clean-build environment isolation under DOD-002/DOD-005). Executing this capability would require building a sandboxed runtime the architecture does not have, not enabling an existing test.",
        "finding": "Measured absence of any isolation primitive or container artifact in the repository.",
        "not_proven": "No sandbox escape or confinement test was executed, because there is no confinement to escape.",
    },
    "GEN-072": {
        "status": "PASS",
        "cites": [
            ("run", "sbom-currency", ["sbom check: ok (720 components, current)"]),
            ("run", "security-check", ["security-check: ok"]),
            ("artifact", ".agent/evidence/sbom/linchpin.cdx.json", ['"bomFormat"', '"CycloneDX"', '"licenses"', "purl"]),
        ],
        "finding": "SBOM generation and verification executed: CycloneDX 1.5 with 720 components and purls on every component, generated from the committed locks by scripts/generate-sbom.py, with a currency check enforced as a lane (it fails if the SBOM drifts from the locks). An earlier defect in which 0 of 720 components carried a purl was measured and fixed.",
        "not_proven": "The SBOM covers Rust and npm components; OS-level and toolchain components are recorded in the environment manifest rather than the SBOM, and no VEX document accompanies it.",
    },
    "GEN-073": {
        "status": "PASS",
        "cites": [
            ("source", "scripts/lint.sh", ["--locked"]),
            ("source", "deny.toml", ["unknown-registry"]),
            ("run", "deny-sources", ["sources ok"]),
            ("run", "deny-bans", []),
        ],
        "finding": "Dependency integrity executed: every enforced build and test lane passes `--locked` so resolution cannot drift from Cargo.lock, cargo-deny verifies crate sources and bans, and the JS graph is installed with a frozen lockfile; the clean-build gate proves the committed locks alone build the workspace.",
        "not_proven": "Hash-level verification of downloaded crates is delegated to Cargo's own checksum verification rather than an independent integrity check, and no signature/attestation verification is performed on registry metadata.",
    },
    "GEN-077": {
        "status": "PASS",
        "cites": [
            ("artifact", ".agent/verification/reports/RELEASE_GATE.json", ["executable_sha256", "msi_sha256"]),
            ("artifact", ".agent/evidence/artifact-e2e/STATUS.md", ["SHA-256"]),
            ("source", "scripts/smoke-installed-artifact.sh", ["msiexec"]),
        ],
        "finding": "Binary integrity verification executed: the release gate pins the SHA-256 and byte size of both the executable and the MSI, the exact-artifact lane records the digest of the binary it drives, and the installer lane installs the real MSI and verifies the installed artifact.",
        "not_proven": "The digests are recorded and checked against the built artifacts, but the release is UNSIGNED (documented limitation in ADR-003), so integrity rests on published digests rather than on an Authenticode signature or attestation.",
    },
    "GEN-081": {
        "status": "PARTIAL",
        "cites": [
            ("probe", "ci_config[.github/workflows]: False"),
            ("probe", "ci_config[.gitlab-ci.yml]: False"),
            ("probe", "ci_config[Jenkinsfile]: False"),
            ("run", "security-check", ["security-check: ok"]),
        ],
        "finding": "The security gates that a pipeline would run are executed and enforced locally, by exit code, in one composed ladder: secret scan, SBOM currency, cargo-deny advisories/bans/sources/licences, pnpm audit, lint, and the unit/integration/artifact lanes.",
        "not_proven": "NOT PASS: no hosted CI configuration exists in this repository (measured: no GitHub Actions, GitLab, Jenkins, CircleCI or Woodpecker config), so nothing prevents a merge that bypasses these gates on a machine that does not run them, and there is no pipeline-runner security posture (secrets scoping, runner isolation, artifact provenance) to test.",
    },
    "GEN-082": {
        "status": "NOT_RUN_BLOCKED_MATERIAL",
        "cites": [
            ("probe", "git_hooks_active: 0"),
            ("probe", "hook_framework[.husky]: False"),
            ("probe", "hook_framework[.pre-commit-config.yaml]: False"),
            ("probe", "root_package_husky_field: False"),
        ],
        "material": "a pre-commit boundary to exercise. Measured: `.git/hooks` contains ZERO active hooks (only `.sample` files) and no hook framework is configured (no .husky, lefthook, pre-commit config or husky field in the root package manifest). The same checks -- secret scan, lint, format, typecheck -- run one step later as enforced gate lanes, and that is recorded rather than used to claim this ID: testing a pre-commit hook requires a hook to exist, and installing one would change the developer workflow for every future candidate without owner authorization.",
        "finding": "Measured absence of any installed git hook or hook framework, with the equivalent later-stage lanes recorded under GEN-001/GEN-005.",
        "not_proven": "No pre-commit hook was tested, because none is installed.",
    },
    "GEN-084": {
        "status": "PASS",
        "cites": [
            ("artifact", ".agent/evidence/artifact-e2e/STATUS.md", ["linchpin-desktop-e2e.exe", "SHA-256"]),
            ("source", "scripts/smoke-installed-artifact.sh", ["msiexec"]),
            ("source", "scripts/artifact-e2e.sh", ["does NOT open a debug port"]),
        ],
        "finding": "Post-build security testing executed on the produced artifact rather than on source: the packaged executable is driven over its real WebView2 instance, asserted to open no debug port, and the installer lane installs, launches and removes the actual MSI.",
        "not_proven": "The post-build checks are behavioural assertions (origin, debug port, confirmation gating, redaction); no binary-hardening audit (ASLR/CFG/DEP flags, symbol stripping, dependency signature check) is performed on the linked image.",
    },
    "GEN-087": {
        "status": "PASS",
        "cites": [
            ("run", "security-check", ["security-check: ok"]),
            ("run", "secret-scan", ["secret-scan check: ok (9 rules, no findings)"]),
            ("artifact", ".agent/verification/reports/RELEASE_GATE.json", ["blocking_clauses"]),
            ("source", "scripts/ship-gate.py", ["NO_GO"]),
        ],
        "finding": "Security gate enforcement executed by exit code, not intention: every scanner lane reports its own status and the gate exits non-zero if any lane fails, one failing lane cannot be masked by a later passing one, and the release verdict is computed from measured state (currently NO_GO with the blocking clause recorded).",
        "not_proven": "Enforcement binds only processes that invoke the ladder; there is no CI runner or branch protection to make it unbypassable (see GEN-081).",
    },
    "GEN-088": {
        "status": "PASS",
        "cites": [
            ("source", "scripts/rerun-invalidated.py", ["NO_RUNNER", "digest"]),
            ("artifact", ".agent/evidence/coverage/SUMMARY.md", ["Generated by `scripts/coverage-gate.py`"]),
            ("probe", "concern[concurrency]_tests: 5"),
        ],
        "finding": "Security test automation executed: every stage is mapped to a concrete repository command, a stage whose runner is missing is reported NO_RUNNER rather than silently skipped, and the commands run with recorded exit codes and output digests; the coverage gate runs each test binary itself rather than trusting a summary.",
        "not_proven": "Automation is a local harness invoked by the operator/agent; scheduling and triggering are not automated (no CI, see GEN-081).",
    },
    "GEN-089": {
        "status": "PASS",
        "cites": [
            ("source", "scripts/change-invalidation.py", ["changed_classes"]),
            ("artifact", ".agent/evidence/coverage/SUMMARY.md", ["Epoch:"]),
            ("artifact", ".agent/verification/state/RERUN_RECORD.json", ["epoch_digest"]),
        ],
        "finding": "Security test orchestration executed through the change-invalidation graph: tracked inputs are grouped into classes, an epoch digest is computed, a change to any class names the stages it invalidates, and the rerun obligation is recorded and enforced (a moved epoch fails the structural validator until the rerun happens).",
        "not_proven": "Orchestration covers the stages the graph knows about; a stage added without registering its inputs would not be invalidated, which is why the stage list is itself checked.",
    },
    "GEN-090": {
        "status": "PASS",
        "cites": [
            ("artifact", ".agent/verification/REQUIREMENT_TRACEABILITY.csv", ["REQ-"]),
            ("source", "scripts/bind-requirements.py", ["covers:"]),
            ("artifact", ".agent/evidence/DOD-037-operator-diagnostics.md", ["alert"]),
        ],
        "finding": "Requirements-driven security testing executed: security-relevant requirements are bound to executed acceptance tests by reading an explicit `covers:` marker from each test's own source, producing a traceability table that currently binds 57 of 59 requirements to executed PASS evidence, with the remaining two recorded EXTERNAL_REQUIRED.",
        "not_proven": "Two requirements (REQ-REL-001, REQ-REL-004) remain unbound because the paths they describe are external; the binding proves a test claims and passes the requirement, not that the requirement is sufficient for the risk.",
    },
    "GEN-098": {
        "status": "PASS",
        "cites": [
            ("artifact", ".agent/evidence/mutation-proof/REPORT.json", ["MUT-OPS-037", "MUT-FUZZ-001", "restored"]),
            ("source", "crates/storage/src/vault.rs", ["test_migration_matrix_preserves_data_from_every_prior_schema"]),
            ("source", "crates/evidence/src/lib.rs", ["test_archive_entry_rejects_zip_slip"]),
        ],
        "finding": "Security control verification executed by controlled defect: thirteen mutations are applied to the controls that matter (credential redaction, traversal guard, truth-boundary guard, keyed-write replay/conflict detection, schema verification, ledger read, diagnostics recording, and the fuzz campaign itself), each caught by its guarding test, restored byte-for-byte and rerun green.",
        "not_proven": "Two further mutations could not be shown to be discriminating and were WITHDRAWN rather than reported as caught, so the proof covers thirteen controls, not every control in the product.",
    },
    "GEN-099": {
        "status": "PASS",
        "cites": [
            ("run", "deny-licenses", ["licenses ok"]),
            ("artifact", ".agent/evidence/sbom/linchpin.cdx.json", ['"licenses"']),
            ("source", "deny.toml", ["MPL-2.0"]),
            ("source", "scripts/generate-sbom.py", ["licenses"]),
        ],
        "finding": "Compliance testing executed for the obligations this repository can satisfy: licence allowlisting enforced in both the cargo-deny gate and the SBOM generator, a waiver register that is empty and validated, and advisory findings disclosed with their threshold.",
        "not_proven": "No regulatory certification, accreditation or legal review is claimed or performed; export-control and patent-practice compliance are outside this harness.",
    },
    "GEN-100": {
        "status": "PASS",
        "cites": [
            ("source", "deny.toml", ["[licenses]", "[bans]"]),
            ("source", "scripts/ship-gate.py", ["NO_GO"]),
            ("run", "lint", ["lint: Done"]),
        ],
        "finding": "Policy-as-code executed: the rules are executable configuration that returns non-zero when violated -- deny.toml for licences/bans/sources/advisories, ESLint and Prettier and TypeScript strictness for source, the applicability matrix that decides pack activation from repository probes, and the ship gate that maps clause statuses to a verdict.",
        "not_proven": "The policies are enforced where the ladder runs; there is no policy engine evaluating infrastructure or runtime state, and no continuous compliance monitor.",
    },
    "GEN-110": {
        "status": "PASS",
        "cites": [
            ("artifact", ".agent/evidence/mutation-proof/REPORT.json", ["MUT-OPS-037"]),
            ("source", "scripts/change-invalidation.py", ["changed_classes"]),
            ("artifact", ".agent/evidence/coverage/SUMMARY.md", ["Epoch:"]),
        ],
        "finding": "Security regression testing executed by three mechanisms together: the mutation harness re-verifies that each guard still discriminates, the coverage gate records the epoch so a source change invalidates the measurement, and the change-invalidation graph re-runs every affected stage after a change.",
        "not_proven": "Regression sensitivity is bounded by the mutations listed (thirteen); a control with no mutation would regress silently, and the harness does not enumerate missing mutations per control.",
    },
    "GEN-112": {
        "status": "PASS",
        "cites": [
            ("artifact", ".agent/evidence/clean-build/STATUS.md", ["| Verdict |", "Checkout"]),
            ("artifact", ".agent/evidence/clean-build/ENVIRONMENT.json", ["toolchain"]),
            ("run", "fmt", []),
            ("run", "lint", ["lint: Done"]),
            ("run", "deny-licenses", ["licenses ok"]),
        ],
        "finding": "Security baseline validation executed: the clean-environment gate materialises an ephemeral checkout with no build output and no installed packages, builds it from the committed locks, runs the whole Rust suite there and proves teardown; format, lint and licence baselines are enforced lanes.",
        "not_proven": "The baseline is a fresh checkout of the same host and toolchain, not a hardened or minimal OS image, so it proves freedom from local state rather than a hardened configuration.",
    },
    "GEN-118": {
        "status": "PASS",
        "cites": [
            ("source", "apps/desktop/src-tauri/src/commands.rs", ["diagnostics_redactor", "record_diagnostic_outcome"]),
            ("artifact", ".agent/evidence/DOD-037-operator-diagnostics.md", ["correlation", "alert"]),
            ("probe", "concern[diagnostics]_tests: 16"),
        ],
        "finding": "Security observability validation executed: recorded command outcomes carry a correlation id and measured duration, alerts derive from those measurements, a fault-injection test asserts DEGRADED plus an alert when storage is absent and a FAILED entry with its policy class when a restore is refused, and everything the surface records passes through the redactor.",
        "not_proven": "Observability is confined to the device-local surface and vault audit chain; there is no log shipping, no tamper-evident off-device store, and no alerting to a human outside the application.",
    },
    "BC-111": {
        "status": "NOT_RUN_BLOCKED_MATERIAL",
        "cites": [
            ("probe", "hardware_key_store_hits: 1"),
            ("source", "crates/platform_windows/src/lib.rs", ["KeyringStore", "MemoryKeyring"]),
            ("source", "crates/domain/src/scope.rs", ["no DPAPI/OS keyring integration"]),
        ],
        "material": "hardware or OS-backed key storage to test. Measured: first-party source contains exactly ONE match for dpapi/ncrypt/CryptAcquireContext/pkcs11/hsm/tpm/cng, and it is the scope map's own limitation sentence (crates/domain/src/scope.rs:58) -- \"the vault itself is a device-local SQLite database, not an OS-encrypted container, and the only KeyringStore is an in-process map (no DPAPI/OS keyring integration)\". The only KeyringStore implementation in the workspace is MemoryKeyring (crates/platform_windows/src/lib.rs:214), which holds keys in process memory, so there is no device, driver or OS key-store operation for an HSM test to exercise. The encrypted-blob container that DOES exist is covered by its own tests under REQ-DATA-006; hardware-backed key storage would be new architecture, not an unrun test.",
        "finding": "Measured absence of any hardware key-store integration, with the product's own scope map stating the limitation.",
        "not_proven": "No HSM/TPM test was executed, because no such device is used by the product and none can be truthfully emulated from this host.",
    },
    "E2E-001": {
        "status": "PASS",
        "cites": [
            ("artifact", ".agent/evidence/clean-build/STATUS.md", ["| Verdict |", "Checkout"]),
            ("source", "scripts/smoke-installed-artifact.sh", ["msiexec"]),
            ("artifact", ".agent/evidence/artifact-e2e/STATUS.md", ["linchpin-desktop-e2e.exe"]),
        ],
        "finding": "Smoke and infrastructure verification executed: the clean-environment gate provisions from committed locks alone and proves teardown, the installer smoke lane installs the real MSI, launches the installed binary to a responsive window and removes it, and the artifact lane drives the packaged executable.",
        "not_proven": "Smoke coverage is the golden path on this host's Windows version; no matrix of supported Windows builds, locales or hardware profiles is exercised.",
    },
    "E2E-005": {
        "status": "PASS",
        "cites": [
            ("artifact", ".agent/verification/state/RERUN_RECORD.json", ["epoch_digest"]),
            ("source", "scripts/change-invalidation.py", ["changed_classes"]),
            ("artifact", ".agent/evidence/mutation-proof/REPORT.json", ["MUT-OPS-037"]),
        ],
        "finding": "Regression and differential verification executed: a change to any tracked input class advances the epoch and obliges a rerun of the affected stages, recorded with commands, exit codes and output digests, while the mutation harness supplies the differential half by proving the guarded behaviour fails when the guard is removed.",
        "not_proven": "Differential comparison is against the guard's absence, not against a previous release build; no historical version-to-version differential run exists (see DOD-035).",
    },
    "E2E-010": {
        "status": "PASS",
        "cites": [
            ("artifact", ".agent/evidence/recovery-drill/report.json", ["objectives_measured", "rto_ms_threshold", "restore_vault (production command)"]),
            ("artifact", ".agent/evidence/stress/STATUS.md", ["concurrent"]),
            ("source", "apps/desktop/src-tauri/tests/recovery_drill.rs", ["fault"]),
        ],
        "finding": "Resilience and recovery verification executed: repeated fault-injected cycles alternate total loss of the vault file with in-place corruption, recovery runs through the production restore command, the recovered state is reconciled by content digest through an independent connection, and RPO/RTO are measured against a stated threshold.",
        "not_proven": "RPO for work committed after the last backup is unbounded and asserted as such: there is no off-device replication, so loss of the device between backups loses that work. The drill covers the vault, not the whole machine.",
    },
    "E2E-015": {
        "status": "PASS",
        "cites": [
            ("source", "apps/desktop/e2e-artifact.mjs", ["canary", "HARD RESTART"]),
            ("artifact", ".agent/evidence/artifact-e2e/STATUS.md", ["confirmation"]),
            ("source", "apps/desktop/src-tauri/src/commands.rs", ["test_export_firewall_blocks_restricted_content"]),
            ("artifact", ".agent/evidence/recovery-drill/report.json", ["read_back_by"]),
        ],
        "finding": "Import/export/data-portability round-trip executed: a runtime canary generated in the product is read back from the durable vault and again after a hard restart, the evidence/package export is confirmation-gated and audited, and the disclosure firewall blocks export of restricted content.",
        "not_proven": "Round-trip coverage is the product's own formats (vault, evidence bundle, filing package); no third-party patent-management or docketing interchange format is implemented or tested.",
    },
    "E2E-008": {
        "status": "PASS",
        "cites": [
            ("artifact", ".agent/evidence/performance/report.json", ['"verdict": "PASS"', "p95_write_ms", "total_write_ms", "limits"]),
            ("source", "apps/desktop/src-tauri/tests/performance_gate.rs", ["p95", "assert"]),
            ("source", "scripts/performance-lane.sh", ["performance_gate"]),
        ],
        "finding": "Performance workload verification executed through its own runnable entry point (`scripts/performance-lane.sh`): 200 conception events written one at a time through the production command into a fresh file-backed vault, every event read back through a SECOND connection, environment recorded, and encoded bounds (p50 50ms, p95 150ms, max 500ms, total write 30s, total read 2s, vault 32MiB) that FAIL the run rather than reporting an observation. The read is asserted to observe every write, so a fast but lossy path cannot pass by dropping work.",
        "not_proven": "The profile is debug and the workload is single-machine, single-process and concurrency-free, so the numbers are regression bounds on this host rather than published service levels; no cost metric is encoded because the product has no metered resource. The pack specifies no numeric performance scale, so the trial defines and labels its own workload.",
    },
    "E2E-009": {
        "status": "PASS",
        "cites": [
            ("artifact", ".agent/evidence/stress/report.json", ["outcomes", "thresholds", "events_lost", "hung_allowed"]),
            ("source", "apps/desktop/src-tauri/tests/stress_concurrency.rs", ["min_throughput_events_per_s", "no backup completed during the trial"]),
            ("source", "scripts/stress-lane.sh", ["stress_concurrency"]),
        ],
        "finding": "Stress/exhaustion verification executed through its own runnable entry point (`scripts/stress-lane.sh`): 8 writer threads x 250 events against one vault with 4 concurrent readers and a backup thread, encoding floors that FAIL the trial (p95 write latency, minimum throughput, no hang, zero lost events, ledger count equals successful writes, zero read failures, zero backup failures) plus non-vacuity assertions that at least one read and one backup completed. The trial FOUND THREE REAL CONCURRENCY DEFECTS (concurrent first open, migration bookkeeping under a race, backup under a lock) and one flaky classification that counted a correct refusal as a failure; all were fixed, and the classification was tightened so a vault that disappears after the first commit still fails.",
        "not_proven": "The workload is one machine, one disk, threads rather than separate processes or hosts, and no stress concurrency level, duration or throughput target is specified in the repository or in the pack's suite library, so the trial labels itself ABBREVIATED and does not claim the clause's full-scale requirement.",
    },
    "E2E-013": {
        "status": "PARTIAL",
        "cites": [
            ("artifact", ".agent/evidence/version-matrix/report.json", ["applicability_notes", "mixed-fleet", "versions"]),
            ("source", "scripts/version-matrix.py", ["mixed-fleet", "payload_exe_sha256"]),
        ],
        "finding": "Version-skew verification is PARTIAL and the missing half is structural rather than pending work: two RELEASED versions exist (v0.1.0 and v0.2.0, each with a distinct MSI and a distinct binary payload digest) and the matrix installs each in sequence with the installed version read back from the Windows Installer registry, so the transitions 0.1.0 -> 0.2.0 -> 0.1.0 are measured rather than assumed.",
        "not_proven": "NOT PASS: simultaneous mixed-fleet skew -- two different versions running at once against shared state -- is NOT APPLICABLE to this product and is recorded as such in the evidence, because it is a single-user desktop application with device-local storage, no server fleet and no shared state, so no such path exists to execute. The two releases also differ only in their version manifests, so behavioural skew between versions is not exercised.",
    },
    "E2E-014": {
        "status": "PASS",
        "cites": [
            ("artifact", ".agent/evidence/version-matrix/report.json", ["downgrade_attempt", "rollback", "matches_shipped_payload", "state_intact"]),
            ("artifact", ".agent/evidence/version-matrix/STATUS.md", ["downgrade_attempt", "rollback"]),
            ("source", "scripts/version-matrix.py", ["refused by Windows Installer", "consistent_with_outcome"]),
        ],
        "finding": "Downgrade and rollback compatibility executed against realistic persistent state: the in-place downgrade from v0.2.0 to v0.1.0 was APPLIED by this installer (exit 0, version back to 0.1.0, shipped-payload digest matched, canary database and blob byte-intact), and the rollback path (uninstall, then reinstall v0.1.0) reconciled the same state. The assertion accepts either installer outcome but requires the installed version to AGREE with the measured exit code, so a refusal with no version change also passes while an exit 0 with the wrong version does not.",
        "not_proven": "The two releases carry the same code with different version manifests, so this proves installer-level downgrade and rollback behaviour with realistic state, not schema downgrade behaviour -- there is no schema to downgrade because no migration was added between the releases.",
    },
    "E2E-018": {
        "status": "DEFERRED_LONG_RUNNING",
        "cites": [
            ("artifact", ".agent/evidence/soak/report.json", ["heartbeats", "max_bytes_per_event", "actual_seconds"]),
            ("source", "apps/desktop/src-tauri/tests/soak_abbreviated.rs", ["ABBREVIATED", "24/48/72+"]),
            ("source", "scripts/soak-lane.sh", ["soak_abbreviated"]),
            ("artifact", ".agent/verification/E2E_SUITE_LIBRARY.md", ["24, 48, 72+ hours", "dedicated"]),
        ],
        "material": "the specified soak scale, which EXISTS and is uncompleted. .agent/verification/E2E_SUITE_LIBRARY.md carries the source of E2E-SoakResourceLeakTesting.md -- the registry's own source_file for E2E-018 -- and it requires 'an extended period (24, 48, 72+ hours)' of sustained nominal load with continuous telemetry and the flatline invariant, and explicitly forbids time-bounded runners, requiring dedicated persistent infrastructure. This host is a shared workstation, not dedicated infrastructure, and cannot supply an uninterrupted multi-day run whose memory and latency slope would mean anything. What IS executed and labeled: an abbreviated endurance trial through the production command with per-heartbeat working-set sampling, run at 600 s in the gate and at 3 600 s as an extended trial recorded separately. DOD-038 is therefore DEFERRED_LONG_RUNNING, never PASS for the full requirement.",
        "finding": "The soak harness exists as a runnable entry point and its abbreviated trials execute with heartbeats and encoded bounds; the clause's specified full-scale duration is uncompleted and the unblock condition is a dedicated host.",
        "not_proven": "Long-duration stability at the specified 24/48/72+ hour scale: no flatline claim is made, no P99-creep-per-day slope is measured, and the abbreviated trials are labeled separately rather than extrapolated.",
    },
    "E2E-019": {
        "status": "PASS",
        "cites": [
            ("artifact", ".agent/evidence/local-provider/STATUS.md", ["smollm2:135m", "transport identity is the local adapter", "non-loopback endpoint is refused"]),
            ("source", "apps/desktop/e2e-local-provider.mjs", ["canary"]),
            ("source", "crates/provider_transport/src/lib.rs", ["test_local_adapter_rejects_non_loopback_endpoint"]),
            ("source", "apps/desktop/src-tauri/src/commands.rs", ["test_local_inference_refuses_non_loopback_endpoint"]),
            ("probe", "loopback_guard_hits: 66"),
            ("probe", "concern[provider]_tests: 9"),
        ],
        "finding": "AI/agentic safety verification executed: the provider lane drives the product's inference command against a real loopback model and asserts a live completion with a runtime canary that must not already exist in the tracked tree, proves the fail-closed negatives (non-loopback endpoint refused with POLICY and no attempt; unreachable endpoint yields a transport error rather than fabricated text), labels AI-origin content distinctly from human conception, and denies MCP capabilities by default.",
        "not_proven": "One small local model is exercised; no adversarial prompt-injection campaign is run against the model, and model-output trustworthiness is bounded by the labelling and the disclosure firewall rather than by output verification.",
    },
    "SUP-002": {
        "status": "PASS",
        "cites": [
            ("artifact", ".agent/verification/REQUIREMENT_TRACEABILITY.csv", ["REQ-"]),
            ("source", "scripts/bind-requirements.py", ["covers:"]),
            ("artifact", ".agent/verification/reports/RELEASE_GATE.json", ["blocking_clauses"]),
            ("artifact", ".agent/evidence/sbom/linchpin.cdx.json", ['"bomFormat"']),
        ],
        "finding": "Requirements-to-release traceability executed: requirement -> executed test -> real result is generated from collected test IDs rather than prose (57 of 59 bound to PASS, 2 EXTERNAL_REQUIRED), and the same artifacts feed the ship gate that computes the release verdict alongside the pinned artifact identity.",
        "not_proven": "Traceability proves a binding to executed evidence; it does not prove the requirement set is complete with respect to the product's risks.",
    },
    "SUP-009": {
        "status": "PASS",
        "cites": [
            ("artifact", ".agent/evidence/documentation/STATUS.md", ["Commands executed: 25 (PASS 22, FAIL 3)"]),
            ("source", "scripts/doc-exec.py", ["SKIPPED"]),
        ],
        "finding": "Executable documentation and quickstart verification executed: commands are extracted from the seven operator-facing documents and run as written, referenced file paths are checked, and the latest full run reports 25 commands executed (22 PASS, 3 accounted failures), 3 skipped with reasons, and no referenced path missing.",
        "not_proven": "The three failures are accounted rather than hidden: the documented NO_GO verdict, the two dev-only advisories, and verify.sh's documented ordering requirement. Documentation was executed on this host only, not across supported Windows versions.",
    },
}


def verify_citation(cite: tuple) -> str:
    """Return a human-readable line for a citation, aborting if it cannot be verified."""
    kind = cite[0]
    if kind == "run":
        _, key, subs = cite
        runs = json.loads(RUNS.read_text(encoding="utf-8"))
        record = next((r for r in runs if r["key"] == key), None)
        if record is None:
            raise SystemExit(f"citation references an uncaptured run: {key}")
        if record["exit_code"] != 0:
            raise SystemExit(f"run {key} exited {record['exit_code']}; it cannot back a PASS claim")
        log = (LOGS / f"{key}.log").read_text(encoding="utf-8", errors="replace")
        for sub in subs:
            if sub not in log:
                raise SystemExit(f"run {key} log does not contain {sub!r}")
        quoted = "; ".join(repr(s) for s in subs) if subs else "exit status only"
        return (
            f"`{' '.join(record['argv'])}` -- exit {record['exit_code']}, output sha256 "
            f"`{record['output_sha256'][:16]}...`, {record['output_bytes']} bytes "
            f"(log `{record['key']}.log`); asserted: {quoted}"
        )
    if kind == "probe":
        line = cite[1]
        text = PROBES.read_text(encoding="utf-8", errors="replace")
        if line not in text:
            raise SystemExit(f"probe line absent from probes.log: {line!r}")
        return f"architecture probe -- `{line}` (captured in `probes.log`)"
    if kind in {"artifact", "source"}:
        _, rel, subs = cite
        path = ROOT / rel
        if not path.exists():
            raise SystemExit(f"cited {kind} does not exist: {rel}")
        text = path.read_text(encoding="utf-8", errors="replace")
        for sub in subs:
            if sub not in text:
                raise SystemExit(f"cited {kind} {rel} does not contain {sub!r}")
        quoted = ", ".join(repr(s) for s in subs)
        label = "evidence artifact" if kind == "artifact" else "first-party source"
        return f"{label} `{rel}` -- quoted and verified: {quoted}"
    raise SystemExit(f"unknown citation kind: {kind}")


def main() -> int:
    check_only = "--check" in sys.argv
    matrix = {r["test_id"]: r for r in csv.DictReader(MATRIX.open(newline="", encoding="utf-8"))}
    registry = {r["test_id"]: r for r in csv.DictReader(REGISTRY.open(newline="", encoding="utf-8"))}
    applicable = {i for i, r in matrix.items() if r["decision"] == "APPLICABLE"}
    covered = {i for i in CASES if i in applicable}
    missing = sorted(applicable - covered - _already_accounted())
    if missing:
        raise SystemExit(f"APPLICABLE IDs with neither a case result nor a case here: {missing}")

    results = json.loads(CASE_RESULTS.read_text(encoding="utf-8")) if CASE_RESULTS.exists() else {"results": []}
    existing = {r["test_id"]: r for r in results.get("results", [])}

    OUT.mkdir(parents=True, exist_ok=True)
    failures = 0
    for test_id in sorted(CASES):
        case = CASES[test_id]
        row = matrix[test_id]
        try:
            lines = [verify_citation(c) for c in case["cites"]]
        except SystemExit as exc:
            print(f"FAIL {test_id}: {exc}", file=sys.stderr)
            failures += 1
            continue

        status = case["status"]
        reason = (
            f"EXECUTED: {'; '.join(lines)}. {case['finding']} "
            + (f"NAMED BLOCKING MATERIAL: {case['material']} " if status == "NOT_RUN_BLOCKED_MATERIAL" else "")
            + f"NOT PROVEN: {case['not_proven']}"
        )
        doc = OUT / f"{test_id}.md"
        body = [
            f"# {test_id} -- {registry[test_id]['title']}",
            "",
            f"**Status: {status}** (recorded in `.agent/verification/state/CASE_RESULTS.json`)",
            "",
            f"- Source group: {row['source_group']}",
            f"- Applicability: {row['decision']} -- {row['evidence']}",
            f"- Generated by `scripts/applicable-case-evidence.py --write`; re-verified by `--check`,",
            "  which fails if any quoted line, symbol or artifact below no longer says what is quoted.",
            "",
            "## Executed check(s)",
            "",
        ]
        body += [f"- {line}" for line in lines]
        body += ["", "## What this establishes", "", case["finding"], ""]
        if status == "NOT_RUN_BLOCKED_MATERIAL":
            body += ["## Named blocking material", "", case["material"], ""]
        body += ["## What this does not establish", "", case["not_proven"], ""]
        body += [
            "## Raw captures",
            "",
            "- Gate logs: `.agent/evidence/applicable-cases/logs/` (see `RUNS.json` for argv, exit",
            "  codes and output digests)",
            "- Architecture probes: `.agent/evidence/applicable-cases/logs/probes.log`",
            "",
        ]
        rendered = "\n".join(body)
        if check_only:
            if not doc.exists() or doc.read_text(encoding="utf-8") != rendered:
                print(f"FAIL {test_id}: evidence document is stale; run --write", file=sys.stderr)
                failures += 1
                continue
            recorded = existing.get(test_id)
            if not recorded or recorded.get("status") != status or recorded.get("evidence_path") != doc.relative_to(ROOT).as_posix():
                print(f"FAIL {test_id}: CASE_RESULTS row disagrees with the case table", file=sys.stderr)
                failures += 1
        else:
            doc.write_text(rendered, encoding="utf-8")
            existing[test_id] = {
                "test_id": test_id,
                "status": status,
                "evidence_path": doc.relative_to(ROOT).as_posix(),
                "reason": reason,
            }

    if check_only:
        if failures:
            print(f"applicable-case-evidence check: FAIL ({failures} IDs)", file=sys.stderr)
            return 1
        print(f"applicable-case-evidence check: ok ({len(CASES)} IDs, {sum(len(c['cites']) for c in CASES.values())} citations verified)")
        return 0

    results["results"] = [existing[k] for k in sorted(existing)]
    # The header identity is stamped from the epoch, because a frozen header lies:
    # measured, CASE_RESULTS.json still claimed candidate '1bca002' and epoch
    # 'EP-009-attempt-002' long after both had moved, and the ship gate was reading
    # that header as the release candidate. RUN_MANIFEST.json remains the
    # authoritative pin; this header is kept consistent with it.
    if EPOCH.exists():
        epoch = json.loads(EPOCH.read_text(encoding="utf-8"))
        results["candidate_commit"] = str(epoch.get("candidate_commit") or "")[:7]
        results["candidate_epoch"] = str(epoch.get("epoch_digest") or "")[:16]
    CASE_RESULTS.write_text(json.dumps(results, indent=2) + "\n", encoding="utf-8")
    tally: dict[str, int] = {}
    for case in CASES.values():
        tally[case["status"]] = tally.get(case["status"], 0) + 1
    print(f"applicable-case-evidence write: {len(CASES)} IDs -> {tally}")
    return 1 if failures else 0


def _already_accounted() -> set[str]:
    """APPLICABLE IDs whose case result predates this script and stays authoritative."""
    if not CASE_RESULTS.exists():
        return set()
    data = json.loads(CASE_RESULTS.read_text(encoding="utf-8"))
    return {r["test_id"] for r in data.get("results", []) if r["test_id"] not in CASES}


if __name__ == "__main__":
    raise SystemExit(main())
