#!/usr/bin/env python3
"""Threat model: validate it against the tree, and render it for readers (GEN-091).

WHY THIS EXISTS. GEN-091 ("Threat Modeling") was recorded NOT_APPLICABLE with the reason
"no threat model document exists in the repository" -- accurate at the time, and closable
by work rather than by an outside party. What makes it a real case rather than a
document anyone could write is BINDING: this validator fails when the model and the code
disagree, so the document cannot rot into security theatre.

It checks, from `.agent/verification/state/THREAT_MODEL.json` against the tree:

  * every STRIDE category is covered by at least one threat;
  * every truth boundary declared in `crates/domain/src/scope.rs` (TB-1..TB-5) is
    modelled, so a boundary added in code cannot go unanalysed;
  * every mitigation NAMES a symbol that exists in the file it cites -- the same
    discipline the applicable-case evidence lane uses, because a mitigation cited
    without its implementation is a claim, not a control;
  * every asset is referenced by at least one threat, and every threat names a declared
    asset and an existing boundary id or "none";
  * every threat carries an explicit residual (or states that it has none), and every
    accepted risk carries a status from the fixed set and the decision that recorded it.

Then it renders `.agent/evidence/threat-model.md`. `--check` re-validates and fails when
the rendered document is stale, so verify.sh can enforce currency the same way it does
for every other derived artefact.
"""
from __future__ import annotations

import json
import pathlib
import re
import sys

ROOT = pathlib.Path(".").resolve()
MODEL = ROOT / ".agent/verification/state/THREAT_MODEL.json"
SCOPE = ROOT / "crates/domain/src/scope.rs"
RENDERED = ROOT / ".agent/evidence/threat-model.md"
STRIDE = {"Spoofing", "Tampering", "Repudiation", "Information disclosure",
          "Denial of service", "Elevation of privilege"}
RISK_STATUS = {"ACCEPTED", "EXTERNAL", "DEFERRED", "OPEN", "CLOSED"}


def truth_boundary_ids() -> list[str]:
    text = SCOPE.read_text(encoding="utf-8")
    start = text.find("TRUTH_BOUNDARIES")
    block = text[start : text.find("];", start)]
    return re.findall(r'id:\s*"(TB-\d+)"', block)


def validate(model: dict) -> list[str]:
    problems: list[str] = []
    assets = {a["id"] for a in model.get("assets", [])}
    threats = model.get("threats", [])

    for stride in STRIDE:
        if not any(t.get("stride") == stride for t in threats):
            problems.append(f"no threat covers STRIDE category {stride!r}")

    declared = truth_boundary_ids()
    if len(declared) != 5:
        problems.append(f"expected 5 truth boundaries in scope.rs, parsed {declared}")
    covered = {entry.get("id") for entry in model.get("truth_boundary_coverage", [])}
    for boundary in declared:
        if boundary not in covered:
            problems.append(f"truth boundary {boundary} is not modelled")
    for boundary in sorted(covered - set(declared)):
        problems.append(f"model covers {boundary}, which scope.rs does not declare")

    referenced: set[str] = set()
    for threat in threats:
        tid = threat.get("id", "?")
        asset = threat.get("asset")
        if asset not in assets:
            problems.append(f"{tid}: names asset {asset!r} which is not declared")
        else:
            referenced.add(asset)
        for symbol in threat.get("mitigation", {}).get("symbols", []):
            path = ROOT / symbol["file"]
            if not path.exists():
                problems.append(f"{tid}: mitigation cites missing file {symbol['file']}")
                continue
            if symbol["contains"] not in path.read_text(encoding="utf-8", errors="replace"):
                problems.append(
                    f"{tid}: mitigation cites {symbol['file']!r} for {symbol['contains']!r}, "
                    "which that file does not contain"
                )
        if not threat.get("mitigation", {}).get("symbols"):
            problems.append(f"{tid}: no mitigation symbol is bound")
        if "residual" not in threat:
            problems.append(f"{tid}: no residual field (state 'none' rather than omitting)")

    for asset in sorted(assets - referenced):
        problems.append(f"asset {asset} is declared but no threat references it")

    for risk in model.get("accepted_risks", []):
        if risk.get("status") not in RISK_STATUS:
            problems.append(f"risk {risk.get('id')}: status {risk.get('status')!r} outside {sorted(RISK_STATUS)}")
        if not risk.get("decision"):
            problems.append(f"risk {risk.get('id')}: no recorded decision")
    return problems


def render(model: dict) -> str:
    lines = [
        "# LINCHPIN threat model (GEN-091)",
        "",
        "Generated by `scripts/check-threat-model.py` from",
        "`.agent/verification/state/THREAT_MODEL.json`. Do not hand-edit: the validator",
        "fails when a mitigation cites a symbol the tree does not contain, when a truth",
        "boundary declared in `crates/domain/src/scope.rs` is not modelled, or when a",
        "STRIDE category is uncovered.",
        "",
        f"- Product: {model['scope']['product']}",
        f"- Deployment: {model['scope']['deployment']}",
        f"- Reviewed: {model['scope']['reviewed']}",
        f"- Method: {model['scope']['method']}",
        "",
        "## Assets",
        "",
        "| ID | Asset | Why it matters |",
        "| --- | --- | --- |",
    ]
    for asset in model["assets"]:
        lines.append(f"| {asset['id']} | {asset['name']} | {asset['why']} |")
    lines += ["", "## Threats", "", "| ID | STRIDE | Asset | Attack | Mitigation | Residual |",
              "| --- | --- | --- | --- | --- | --- |"]
    for threat in model["threats"]:
        mitigation = threat["mitigation"]["summary"]
        residual = threat["residual"]
        lines.append(
            f"| {threat['id']} | {threat['stride']} | {threat['asset']} | {threat['attack']} | "
            f"{mitigation} | {residual} |"
        )
    lines += ["", "### Mitigation bindings", "",
              "Each row below is checked: the file must exist and must contain the quoted text.",
              "", "| Threat | File | Contains |", "| --- | --- | --- |"]
    for threat in model["threats"]:
        for symbol in threat["mitigation"]["symbols"]:
            lines.append(f"| {threat['id']} | `{symbol['file']}` | `{symbol['contains']}` |")
    lines += ["", "## Truth boundary coverage", "", "| Boundary | Threats | Note |", "| --- | --- | --- |"]
    for entry in model["truth_boundary_coverage"]:
        lines.append(f"| {entry['id']} | {', '.join(entry['threats'])} | {entry['note']} |")
    lines += ["", "## Accepted, external, deferred and open risks", "",
              "| ID | Risk | Status | Decision | Owner |", "| --- | --- | --- | --- | --- |"]
    for risk in model["accepted_risks"]:
        lines.append(
            f"| {risk['id']} | {risk['risk']} | {risk['status']} | {risk['decision']} | {risk['owner']} |"
        )
    lines += ["", "## Reproduce", "", "```", "python3 scripts/check-threat-model.py",
              "python3 scripts/check-threat-model.py --check", "```", ""]
    return "\n".join(lines)


def main() -> int:
    check_only = "--check" in sys.argv
    if not MODEL.exists():
        print(f"threat-model: FAIL -- no model at {MODEL}", file=sys.stderr)
        return 1
    model = json.loads(MODEL.read_text(encoding="utf-8"))
    problems = validate(model)
    if problems:
        print(f"threat-model: FAIL -- {len(problems)} problem(s) between the model and the tree:", file=sys.stderr)
        for problem in problems:
            print(f"  {problem}", file=sys.stderr)
        return 1
    rendered = render(model)
    if check_only:
        if not RENDERED.exists() or RENDERED.read_text(encoding="utf-8") != rendered:
            print("threat-model: FAIL -- rendered document is stale; run without --check", file=sys.stderr)
            return 1
        print(
            f"threat-model check: ok ({len(model['threats'])} threats, "
            f"{len(model['assets'])} assets, {len(model['accepted_risks'])} recorded risks, "
            f"every mitigation symbol present in the tree)"
        )
        return 0
    RENDERED.parent.mkdir(parents=True, exist_ok=True)
    RENDERED.write_text(rendered, encoding="utf-8")
    print(
        f"threat-model: wrote {RENDERED.relative_to(ROOT)} "
        f"({len(model['threats'])} threats, {len(model['accepted_risks'])} risks)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
