"""Generate the human-readable evidence index (DOD-025).

DOD-025 REQUIRED EVIDENCE: "Evidence index entries and content hashes linked to
each result." The machine-readable form lives in DOD_STATUS.jsonl and
TEST_LEDGER.jsonl; this renders the same mapping as a reviewable document so a
reader does not have to parse JSONL to see what each claim rests on.

This file is generated. Regenerate with `python3 scripts/generate-evidence-index.py`
after any status rebuild; `--check` verifies it is current.
"""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

DOD = Path(".agent/verification/state/DOD_STATUS.jsonl")
LEDGER = Path(".agent/verification/state/TEST_LEDGER.jsonl")
OUT = Path(".agent/evidence/EVIDENCE_HASHES.md")


def digest(path: str | None) -> str | None:
    if not path:
        return None
    p = Path(path)
    return hashlib.sha256(p.read_bytes()).hexdigest() if p.is_file() else None


def main() -> int:
    rows = [json.loads(l) for l in DOD.read_text("utf-8").splitlines() if l.strip()]
    ledger = [json.loads(l) for l in LEDGER.read_text("utf-8").splitlines() if l.strip()]

    lines = [
        "# Evidence Index and Content Hashes",
        "",
        "Generated by `scripts/generate-evidence-index.py`. Do not hand-edit.",
        "",
        "DOD-025 requires evidence index entries and content hashes linked to each",
        "result. Each row below is the digest of the evidence document that the",
        "named result rests on, as of the current candidate. If a cited document",
        "changes, the corresponding `--check` fails and names the affected result,",
        "so a PASS cannot outlive the evidence that justified it (DOD-040).",
        "",
        f"- DOD dispositions: {len(rows)}",
        f"- Registry ledger rows: {len(ledger)}",
        "",
        "## DOD clause dispositions",
        "",
        "| Clause | Status | Evidence | sha256 | Bytes |",
        "| --- | --- | --- | --- | --- |",
    ]
    stale = 0
    for r in sorted(rows, key=lambda x: x["dod_id"]):
        recorded = r.get("evidence_sha256")
        current = digest(r.get("evidence_path"))
        marker = "" if recorded == current else " **(STALE)**"
        if recorded != current:
            stale += 1
        lines.append(
            f"| {r['dod_id']} | {r['status']} | `{r['evidence_path']}`{marker} | "
            f"`{(recorded or 'none')[:16]}` | {r.get('evidence_bytes')} |"
        )

    lines += [
        "",
        "## Registry ledger rows with a cited evidence document",
        "",
        "Only rows that cite a document are listed; the remainder are",
        "`NOT_RUN_BLOCKED_MATERIAL` with no case material yet, which is recorded",
        "in `COMPLETE_TEST_ACCOUNTING.csv` rather than hidden.",
        "",
        "| Test ID | Status | Evidence | sha256 |",
        "| --- | --- | --- | --- |",
    ]
    cited = 0
    for r in ledger:
        if not r.get("evidence_path"):
            continue
        cited += 1
        recorded = r.get("evidence_sha256")
        current = digest(r.get("evidence_path"))
        marker = "" if recorded == current else " **(STALE)**"
        if recorded != current:
            stale += 1
        lines.append(
            f"| {r['test_id']} | {r['final_status']} | `{r['evidence_path']}`{marker} | "
            f"`{(recorded or 'none')[:16]}` |"
        )
    lines += [
        "",
        f"Ledger rows citing a document: {cited} of {len(ledger)}.",
        "",
        "## Verification",
        "",
        "```text",
        "python3 scripts/build-dod-status.py --check     # 42 clause digests current",
        "python3 scripts/build-accounting.py --check     # 484 ledger digests current",
        "```",
        "",
        f"Stale entries at generation time: {stale}.",
        "",
    ]

    if "--check" in sys.argv:
        if "--structure-only" in sys.argv:
            # harness-validate.sh path: presence and shape only. The file's
            # CONTENT is derived from the digests, so asserting freshness there
            # would be circular; verify.sh asserts it once the state has settled.
            if not OUT.exists():
                print("evidence-index check: FAIL (file missing)", file=sys.stderr)
                return 1
            print(f"evidence-index check: ok ({len(rows)} clauses, structure only)")
            return 0
        if not OUT.exists():
            print("evidence-index check: FAIL (file missing)", file=sys.stderr)
            return 1
        if OUT.read_text("utf-8") != "\n".join(lines):
            print(
                "evidence-index check: FAIL (regenerate with "
                "scripts/generate-evidence-index.py)",
                file=sys.stderr,
            )
            return 1
        print(f"evidence-index check: ok ({len(rows)} clauses, {cited} ledger rows)")
        return 0

    OUT.write_text("\n".join(lines), "utf-8")
    print(f"wrote {OUT} ({len(rows)} clauses, {cited} ledger rows, {stale} stale)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
