#!/usr/bin/env bash
# Full verification ladder.
#
# Ordered so that the epoch-sensitive steps come LAST: running any build or test
# gate can change the epoch, so the change-invalidation and rerun checks are only
# meaningful once everything before them has settled.
#
# BUG FIXED: the previous version ended with `sh scripts/security-check.sh`,
# whose own `set -eu` trailing-`&&` bug (since fixed) made this script's exit
# status depend on whether package.json existed rather than on the gates. Each
# lane now reports its own status and the script fails if any lane fails.
set -eu

status=0
run() {
  name="$1"; shift
  echo "=== verify: $name"
  if "$@"; then
    echo "    $name: ok"
  else
    code=$?
    echo "    $name: FAIL (exit $code)" >&2
    status=1
  fi
}

run "pack validation" python3 scripts/validate-generated-pack.py .
run "lint" sh scripts/lint.sh
run "format-check" sh scripts/format-check.sh
run "typecheck" sh scripts/typecheck.sh
run "unit tests" sh scripts/test-unit.sh
run "integration tests" sh scripts/test-integration.sh
run "security" sh scripts/security-check.sh

# Epoch-sensitive checks, LAST and in this order.
#
# `change-invalidation.py` (without --check) must run first: it RECOMPUTES and
# records the epoch. Only then can --check pass and a rerun be meaningful.
# Without this, every lane above that touches a tracked input advances the epoch
# and leaves the recorded record stale, which is what happened when the checks
# were simply appended.
run "change invalidation (recompute)" python3 scripts/change-invalidation.py
run "change invalidation (verify)" python3 scripts/change-invalidation.py --check
run "rerun obligation" python3 scripts/rerun-invalidated.py --check

# Evidence-currency checks, AFTER the epoch has settled.
#
# These live here rather than in harness-validate.sh because harness-validate is
# itself an invalidated stage: a gate change reruns it, and the stages that
# rewrite evidence run before it, so a currency check inside it can never pass
# on a rerun. That is the same circularity that forced the rerun-obligation
# check out of harness-validate earlier; harness-validate now runs these with
# --structure-only and the currency assertion happens here, on the settled state.
run "ledger evidence currency" python3 scripts/build-accounting.py --check
run "DOD evidence currency" python3 scripts/build-dod-status.py --check
run "evidence index currency" python3 scripts/generate-evidence-index.py --check

# DOD-030 registry accounting currency: the 41 APPLICABLE IDs that carry an
# executed case cite gate logs, architecture probes, source symbols and evidence
# artifacts BY QUOTED LINE. Those artifacts are regenerated by the settle path, so
# a quote can silently go stale; this lane re-reads every citation and fails if a
# quoted line, symbol or artifact no longer says what the evidence document claims.
# Re-derive with `python3 scripts/applicable-case-evidence.py --write`.
run "applicable-case evidence currency" python3 scripts/applicable-case-evidence.py --check

# EP-010 M1 stage accounting currency: the per-stage record is derived from the
# registry, the applicability matrix and the per-ID accounting, all three of which
# the settle path rewrites. This lane fails when the derived record no longer
# matches them, so a stage verdict cannot silently describe a superseded state.
# Re-derive with `python3 scripts/stage-accounting.py`.
run "stage accounting currency" python3 scripts/stage-accounting.py --check

# EP-010 M3 drift currency: the drift record pins the digests of ARCHITECTURE.md,
# the scope module and the crate manifests, so a spec or dependency change fails
# here until the accounting is re-derived.
run "architecture drift currency" python3 scripts/architecture-drift.py --check

# EP-010 M4/M5 residual-risk, readiness, next-action, submit-report and manual-release
# documents are DERIVED from the state files. Two of them used to be pack templates
# that had become false statements about this run; this lane fails the moment any of
# them stops matching the evidence they describe.
run "residual risk / readiness currency" python3 scripts/residual-risk-report.py --check

# DOD-040 artifact currency for the cross-version matrix: the staged v0.1.0/v0.2.0
# packages must have been built from the source that is in the tree NOW. Measured
# defect this closes: the matrix ran against artifacts built the previous day while
# production code changed, and its PASS described a candidate that no longer
# existed. Rebuild with `python3 scripts/version-matrix.py --provision`.
run "version-matrix source currency" python3 scripts/version-matrix.py --check-source

# GEN-091 threat-model currency: the model is only worth having if it is BOUND to the
# code. This lane re-reads every mitigation symbol, every truth boundary declared in
# crates/domain/src/scope.rs, every STRIDE category and every recorded risk, and fails
# when the model and the tree disagree or the rendered document is stale.
run "threat-model currency" python3 scripts/check-threat-model.py --check

# GEN-092 attack-tree currency: the trees are bound to the threat model and to the code
# the same way the model is -- every MITIGATED leaf must cite a symbol the tree contains,
# every OPEN/PARTIAL leaf must carry a residual traceable to the risk register, and every
# modelled threat must be either represented or explicitly noted.
run "attack-tree currency" python3 scripts/check-attack-trees.py --check

# GEN-058 weak-cryptography detection: scans code use and both locked graphs, and its
# self-test proves the scanner discriminates (a gate that finds nothing must show it can
# find something).
run "weak-crypto scan" python3 scripts/weak-crypto-scan.py
run "weak-crypto self-test" python3 scripts/weak-crypto-scan.py --self-test

# GEN-043 advisory assessment: every advisory a scanner reports must carry a decision with
# its reachability stated. This lane re-runs both scanners, so a new advisory arriving
# without an assessment fails here rather than sliding into the release unnoticed.
run "advisory assessment" python3 scripts/assess-advisories.py

# GEN-013 / GEN-014 code metrics: complexity, unsafe blocks and panicking calls with
# ENFORCED ceilings, plus a self-test that proves the measurement sees a planted defect.
run "code metrics" python3 scripts/code-metrics.py
run "code metrics self-test" python3 scripts/code-metrics.py --self-test

# EP-010 M3 architecture drift accounting (AGENTS.md section 6): truth boundaries
# transcribed verbatim into code, import/dependency law, dead workspace edges and
# non-loopback URL literals in production source, plus the review items bound to the
# gates that prove them. The self-test plants one violation per mechanical rule.
run "architecture drift" python3 scripts/architecture-drift.py
run "architecture drift self-test" python3 scripts/architecture-drift.py --self-test

# The STRICT ship-gate check lives here, after the settle refresh: the recorded
# RELEASE_GATE.json must match the recomputed verdict, artifact identity, clause lists
# and tallies exactly. harness-validate (stage V-000) uses --structure-only because it
# runs before the refresh, so this lane is where the identity comparison can hold --
# and it fails when the pinned installer's bytes move under the recorded identity.
run "ship gate currency" python3 scripts/ship-gate.py --check

# Identity check LAST, after the epoch has settled: DOD-029 requires the
# candidate commit, base revision, epoch and artifact digests to belong to the
# SAME run, and this lane fails when any of them has moved since the manifest was
# written. Re-derive with `python3 scripts/run-manifest.py` after settling.
run "run manifest identity" python3 scripts/run-manifest.py --check
run "completion report" python3 scripts/completion-report.py --check

# DOD-008 evidence currency: the coverage report records the EPOCH it was measured
# at, so a source change invalidates the number instead of leaving a stale one in
# place. Re-measure with `python3 scripts/coverage-gate.py` (the settle path does
# this automatically).
run "coverage currency" python3 scripts/coverage-gate.py --check

if [ "$status" -eq 0 ]; then
  echo "verify: ok"
else
  echo "verify: FAIL -- see the lanes above" >&2
fi
exit "$status"
